networks:
  trace2e_network:
    driver: bridge

services:
  trace2e_0:
    build:
      context: .
      dockerfile: trace2e.Dockerfile
    hostname: trace2e_0
    container_name: trace2e_0
    networks:
      - trace2e_network

  trace2e_1:
    build:
      context: .
      dockerfile: trace2e.Dockerfile
    hostname: trace2e_1
    container_name: trace2e_1
    networks:
      - trace2e_network

  trace2e_tests_0:
    build:
      context: .
      dockerfile: trace2e-testsuite.Dockerfile
    hostname: trace2e_tests_0
    container_name: trace2e_tests_0
    networks:
      - trace2e_network
