use_small_heuristics = "Max"
trailing_semicolon = false
use_field_init_shorthand = true
reorder_imports = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
comment_width = 100
wrap_comments = true
doc_comment_code_block_width = 100
format_code_in_doc_comments = true