networks:
  trace2e_network:
    driver: bridge

services:
  hyper_server:
    build:
      context: ../../
      dockerfile: demo/trace2e.Dockerfile
      target: hyper_server_runtime
    hostname: hyper_server
    container_name: hyper_server
    networks:
      - trace2e_network
    restart: unless-stopped
    entrypoint: >
      sh -c "/hypere2e_server & /hypere2e_gateway & /hyper_server & /hyper_gateway & RUST_LOG="trace2e_middleware::traceability=debug,trace2e_middleware::m2m_service=info,trace2e_middleware::p2m_service=info" /trace2e_middleware"


  hyper_client:
    build:
      context: ../../
      dockerfile: demo/trace2e.Dockerfile
      target: hyper_client_runtime
    hostname: hyper_client
    container_name: hyper_client
    networks:
      - trace2e_network
    stdin_open: true
    tty: true
    depends_on:
      - hyper_server
    entrypoint: >
      sh -c "/trace2e_middleware & bash"

