networks:
  trace2e_network:
    driver: bridge

services:
  trace2e_base:
    build:
      context: ../../
      dockerfile: demo/base/trace2e-base.Dockerfile
    image: trace2e-base

  hyper_server:
    build:
      context: ../../
      dockerfile: demo/hyper/trace2e-hyper-server.Dockerfile
    hostname: hyper_server
    container_name: hyper_server
    networks:
      - trace2e_network
    restart: unless-stopped
    depends_on:
      - trace2e_base
    entrypoint: >
      sh -c "/hypere2e_server & /hypere2e_gateway & /hyper_server & /hyper_gateway & RUST_LOG="trace2e_middleware::traceability=debug,trace2e_middleware::m2m_service=info,trace2e_middleware::p2m_service=info" /trace2e_middleware"

  hyper_client:
    build:
      context: ../../
      dockerfile: demo/hyper/trace2e-hyper-client.Dockerfile
    hostname: hyper_client
    container_name: hyper_client
    networks:
      - trace2e_network
    stdin_open: true
    tty: true
    depends_on:
      - trace2e_base
      - hyper_server
    volumes:
      - ./scripts:/scripts
    entrypoint: >
      sh -c "/trace2e_middleware & bash"

