name: CI

on:
  push:
    branches: [ "master" ]
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup
      uses: ./.github/actions/rust-setup
      with:
        protoc: true
        components: "clippy, rustfmt"

    - name: Code formatting check
      run: make fmt
      shell: bash

    - name: Run clippy
      run: make clippy
      shell: bash

  middleware-tests:
    runs-on: ubuntu-latest
    needs: lint
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup
      uses: ./.github/actions/rust-setup
      with:
        protoc: true

    - name: Run middleware tests
      run: make test-middleware
      shell: bash

  lib-tests:
    runs-on: ubuntu-latest
    needs: lint
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup
      uses: ./.github/actions/rust-setup
      with:
        protoc: true

    - name: Run integration tests
      run: make test-lib
      shell: bash