name: CI

on:
  push:
    branches: [ "master" ]
  pull_request: {}

env:
  PROTOC_VERSION: 3.21.12
  CARGO_TERM_COLOR: always

jobs:
  trace2e:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install protoc
      uses: taiki-e/install-action@v2
      with:
        tool: protoc@${{ env.PROTOC_VERSION }}
    - name: Run tests
      run: ./tests.sh
      shell: bash
