name: CI

on:
  push:
    branches: [ "master" ]
  pull_request: {}

env:
  PROTOC_VERSION: 3.21.12
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Install protoc
      uses: taiki-e/install-action@v2
      with:
        tool: protoc@${{ env.PROTOC_VERSION }}
    - name: Code formatting check
      run: make fmt
      shell: bash
    - name: Run clippy
      run: make clippy
      shell: bash

  middleware-tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v5
    - name: Install protoc
      uses: taiki-e/install-action@v2
      with:
        tool: protoc@${{ env.PROTOC_VERSION }}
    - name: Run middleware tests
      run: make test-middleware
      shell: bash

  lib-tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v5
    - name: Install protoc
      uses: taiki-e/install-action@v2
      with:
        tool: protoc@${{ env.PROTOC_VERSION }}
    - name: Run integration tests
      run: make test-lib
      shell: bash