name: CI

on:
  push:
    branches: [ "master" ]
  pull_request: {}

env:
  PROTOC_VERSION: 3.21.12
  CARGO_TERM_COLOR: always

jobs:
  trace2e:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install protoc
      uses: taiki-e/install-action@v2
      with:
        tool: protoc@${{ env.PROTOC_VERSION }}
    - name: Code formatting check
      run: cargo fmt --check
      shell: bash
    - name: Run clippy (trace2e_middleware)
      run: cargo clippy -p trace2e_middleware
      shell: bash
    - name: Run middleware tests
      run: cargo test -p trace2e_middleware
      shell: bash
    - name: Run custom lib tests
      run: cargo run --release -p trace2e_middleware & ; TRACE2E_PID=$! ; cargo test -p stde2e; kill ${TRACE2E_PID}
      shell: bash