name: CI

on:
  push:
    branches: [ "master" ]
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  trace2e:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run integration tests
      run: ./integration_tests.sh
      shell: bash
